### ISSUE TITLE
Could not find any composer autoloaders in /github/workspace/

### ISSUE THREAD

**Issue by vudaltsov** [mickaelandrieu/psalm-ga#2]
See: https://github.com/vudaltsov/exceptionally/pull/1/checks?check_run_id=184497913

**Comment by sagikazarmark** [comment]
You need to install dependencies with composer first:

```
      - name: Install
        uses: docker://composer
        with:
          args: install --ignore-platform-reqs
```
